name: DungeonCrawler
version: 1.0
main: com.crypticvortex.dc.DungeonCrawler
description: A Dungeon Crawler game mode designed in Minecraft!
commands:
  tutorial:
    description: Displays categories for tutorial messages.
    usage: tutorial
  populate:
    description: Debugging command for the LootGenerator
    usage: populate
  item:
    description: Debugging command to retrieve item from LootTable.
    usage: item [percent] [index]
  spawn:
    description: Debugging command to spawn entities from the MobTable.
    usage: spawn [name]
  class:
    description: Changes your current class.
    usage: class [name]
  reset:
    description: Resets all broken blocks and all spawners to their original states.
    usage: reset